import type { VercelRequest, VercelResponse } from '@vercel/node';
import crypto from 'crypto';
import { supabaseAdmin } from './_supabaseAdmin.js';

export const config = {
  api: {
    bodyParser: false,
  },
};

const LINE_REPLY_URL = 'https://api.line.me/v2/bot/message/reply';

async function readRawBody(req: VercelRequest): Promise<Buffer> {
  const chunks: Buffer[] = [];
  for await (const chunk of req) {
    chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
  }
  return Buffer.concat(chunks);
}

interface LineEvent {
  type: string;
  replyToken?: string;
  source?: { type: string; userId?: string };
  message?: { type: string; text?: string };
}

async function reply(accessToken: string, replyToken: string, text: string): Promise<void> {
  await fetch(LINE_REPLY_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${accessToken}`,
    },
    body: JSON.stringify({
      replyToken,
      messages: [{ type: 'text', text }],
    }),
  });
}

interface NotifSettingsRow {
  lineLinkCode?: string;
  lineLinkCodeExpiresAt?: string;
  [key: string]: unknown;
}

// Matches an incoming message's text against any account's pending link code (generated by
// api/line-link-code.ts from Settings) and links that account's lineUserId on a match --
// self-service, no manual "look up your ID and send it to support" step needed.
async function tryLinkAccount(userId: string, messageText: string): Promise<boolean> {
  const code = messageText.trim().toUpperCase();
  if (!code) return false;

  const { data: rows, error } = await supabaseAdmin
    .from('user_cashflow_data')
    .select('user_id, notif_settings')
    .not('notif_settings->>lineLinkCode', 'is', null);
  if (error) {
    console.error('line-webhook: failed to look up pending link codes:', error);
    return false;
  }

  const now = Date.now();
  const match = (rows || []).find((row) => {
    const ns: NotifSettingsRow = row.notif_settings || {};
    if (!ns.lineLinkCode || ns.lineLinkCode.toUpperCase() !== code) return false;
    if (ns.lineLinkCodeExpiresAt && new Date(ns.lineLinkCodeExpiresAt).getTime() < now) return false;
    return true;
  });
  if (!match) return false;

  const ns: NotifSettingsRow = match.notif_settings || {};
  const { lineLinkCode, lineLinkCodeExpiresAt, ...restNotifSettings } = ns;

  const { error: updateErr } = await supabaseAdmin
    .from('user_cashflow_data')
    .update({ notif_settings: { ...restNotifSettings, lineUserId: userId } })
    .eq('user_id', match.user_id);

  if (updateErr) {
    console.error('line-webhook: failed to save linked lineUserId:', updateErr);
    return false;
  }
  return true;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const channelSecret = process.env.LINE_CHANNEL_SECRET;
  const accessToken = process.env.LINE_CHANNEL_ACCESS_TOKEN;
  if (!channelSecret || !accessToken) {
    res.status(500).json({ error: 'Missing LINE_CHANNEL_SECRET or LINE_CHANNEL_ACCESS_TOKEN' });
    return;
  }

  const rawBody = await readRawBody(req);
  const signature = req.headers['x-line-signature'];
  const expectedSignature = crypto.createHmac('sha256', channelSecret).update(rawBody).digest('base64');
  if (typeof signature !== 'string' || signature !== expectedSignature) {
    res.status(401).json({ error: 'Invalid signature' });
    return;
  }

  try {
    const body = JSON.parse(rawBody.toString('utf-8')) as { events?: LineEvent[] };
    const events = body.events || [];

    await Promise.all(
      events.map(async (event) => {
        if (event.type !== 'message' || event.message?.type !== 'text' || !event.replyToken) return;
        const lineUserId = event.source?.userId;
        if (event.source?.type !== 'user' || !lineUserId) return;

        const linked = await tryLinkAccount(lineUserId, event.message.text || '');
        const replyText = linked
          ? '✅ เชื่อมต่อบัญชีสำเร็จแล้วครับ!\nตอนนี้คุณจะได้รับแจ้งเตือนจากกระรอกตุนเงินผ่าน LINE นี้แล้ว'
          : 'ไม่พบรหัสเชื่อมต่อที่ตรงกันครับ ไปที่หน้าตั้งค่าในแอปกระรอกตุนเงิน > เชื่อมต่อ LINE เพื่อรับรหัสใหม่ แล้วส่งรหัสนั้นมาที่นี่ครับ';

        await reply(accessToken, event.replyToken, replyText);
      })
    );

    res.status(200).json({ ok: true });
  } catch (err: any) {
    console.error('line-webhook handler error:', err);
    res.status(500).json({ error: err.message || 'Webhook handler failed' });
  }
}
